#!/bin/sh

alias v='vim'
alias nv='nvim'
alias em="emacsclient -c -a 'emacs'"
ex ()
{
  if [ -f "$1" ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.tar.xz)    tar xf $1    ;;
      *.tar.zst)   unzstd $1    ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# cd() {
#     builtin cd $@
#     echo -ne "\033]0;$(pwd | sed -e "s@$HOME@~@g")\007"
# }

u () {
  local d=""
  local limit="$1"

  # Default to limit of 1
  if [ -z "$limit" ] || [ "$limit" -le 0 ]; then
    limit=1
  fi

  for ((i=1;i<=limit;i++)); do
    d="../$d"
  done

  # perform cd. Show error if cd fails
  if ! cd "$d"; then
    echo "Couldn't go up $limit dirs.";
  fi
}

lf () {
	LF_TEMPDIR="$(mktemp -d -t lf-tempdir-XXXXXX)"
	LF_TEMPDIR="$LF_TEMPDIR" lfrun -last-dir-path="$LF_TEMPDIR/lastdir" "$@"
	if [ "$(cat "$LF_TEMPDIR/cdtolastdir" 2>/dev/null)" = "1" ]; then
		cd "$(cat "$LF_TEMPDIR/lastdir")"
	fi
	#rm -r "$LF_TEMPDIR"
	unset LF_TEMPDIR
}

share() {
  curl -F"file=@$*" https://0x0.st
}

alias ls='exa --color=always --icons --group-directories-first'
alias la='exa -a --color=always --icons --group-directories-first'
alias lt='exa -aT --color=always --icons --group-directories-first'
alias l.='exa -a | egrep "^\."'
alias ll='exa -l --color=always --icons --group-directories-first'

alias nnvim="NVIM_APPNAME=nvim.new nvim"
alias lvim="NVIM_APPNAME=lvim nvim"
alias lunarvim="NVIM_APPNAME=lunarvim nvim"
alias lazyvim="NVIM_APPNAME=lazyvim nvim"

alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias z="zathura --fork"

alias spac="sudo pacman"
alias ytdl='youtube-dl'
alias ytdlm='youtube-dl -f bestaudio --extract-audio --audio-format flac --audio-quality 0'
alias ytdlp='youtube-dl -f "bestaudio/best" -ciw -o "%(title)s.%(ext)s" -v --extract-audio --audio-format mp3 --audio-quality 0  --yes-playlist'
alias ncm='ncmpcpp'

# trash cli
alias tput='trash-put'
alias empty='trash-empty'
alias tlist='trash-list'
alias trest='trash-restore'

alias t="touch"
alias mkd="mkdir -pv"
alias topdf="soffice --headless --convert-to pdf"
alias jstris="devour librewolf -P default-release ~/Jstris.html"

alias ff="fastfetch --structure OS:Kernel:Shell:DE:WM:WMTheme:Theme:Icons:Font:Cursor:Terminal:TerminalFont:Colors"
alias rrun="Rscript"
alias py="python3"
alias py36="/usr/bin/python3.6"
alias py2="python2"
alias g20="g++ -std=c++20 -Wshadow -Wall -Weffc++ -Wextra -Wconversion -Wsign-conversion --pedantic-errors"
alias g23="g++ -std=c++23 -Wshadow -Wall -Weffc++ -Wextra -Wconversion -Wsign-conversion --pedantic-errors"
alias g17="g++ -std=c++17 -Wshadow -Wall -Weffc++ -Wextra -Wconversion -Wsign-conversion --pedantic-errors"
alias cm="cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1"
alias rsy="rsync -aruzv --partial --checksum"
alias rsyd="rsync -aruvz --partial --checksum --delete --backup --backup-dir=DELETED_FILES/"
alias rsjgeor="rsync -rtzvP ~/documents/07_code/projects/personal-website/ root@jgeor.com:/var/www/jgeor"
alias con="nmcli device wifi connect"

alias lpdshort="lp -o sides=two-sided-short-edge -o BindEdge=Top"
alias lpdlong="lp -o sides=two-sided-long-edge -o BindEdge=Left"

alias addup='git add -u'
alias addall='git add .'
alias up="git add .; git commit -m 'asdf'; push"
alias branch='git branch'
alias checkout='git checkout'
alias clone='git clone'
alias commit='git commit'
alias fetch='git fetch'
alias pull='git pull origin'
alias push='git push origin'
alias stat='git status'  # 'status' is protected name so using 'stat' instead
alias tag='git tag'
alias newtag='git tag -a'
