#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# WM CONFIG
bspc monitor -d dir www doc sys mus com ac1 ac2 ac3 ac4 

bspc config window_gap             -1
bspc config top_padding 	       29
bspc config left_padding           11
bspc config right_padding          11
bspc config bottom_padding         11
bspc config border_width           1

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true 

bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled 
bspc rule -a Tk state=floating
bspc rule -a matplotlib state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Lab state=floating


# SCRATCHPADR
scratchpad_xy="1200x800"
display_xy=$(xdpyinfo | grep -i dimensions | awk '{ print $2 }')
half_display=$(echo $display_xy | tr 'x' ' ' | cut -f1 -d' ' | xargs -I _ echo _/2 | bc)
half_scratchpad=$(echo $scratchpad_xy | tr 'x' ' ' | cut -f1 -d' ' | xargs -I _ echo _/2 | bc)
offset=$(echo ${half_display}-${half_scratchpad} | bc)
bspc rule -a scpad sticky=on state=floating rectangle=${scratchpad_xy}+${offset}+60

# BORDER COLORS
bspc config normal_border_color "#0c0e0f"
bspc config active_border_color "#b3c1c1"
bspc config focused_border_color "#b3c1c1"
# bspc config active_border_color "#232a2d"
# bspc config focused_border_color "#232a2d"

# STARTUP PROGRAMS
#
sxhkd &
$HOME/.config/polybar/launch.sh &
picom &
wal -R &
dunst &
rm /tmp/polybarhidden & 
fehbg &
# EXTRA CONFIG
setxkbmap -option caps:escape &
xset -dpms &
xset r rate 215 45 &
setxkbmap us & 
$HOME/documents/scripts_config/extra
