#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 


bspc config window_gap              0
bspc config top_padding 	       0
bspc config left_padding           0
bspc config right_padding          0
bspc config bottom_padding         0
bspc config border_width           1

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true 

bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled 
bspc rule -a Tk state=floating
bspc rule -a Emacs state=tiled

# Set the border colors.
bspc config normal_border_color "#111111"
bspc config active_border_color "#223232"
bspc config focused_border_color "#223232"
sxhkd & 
$HOME/.config/polybar/launch.sh
