#!/bin/bash

notif () {
    volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{printf "%.0f%%", $2 * 100}')
    dunstify -a "changevolume" -r 9993 -h int:value:"$volume" -I "/home/joseph/.local/share/dunst_icons/volume-$1.svg" "${volume}" -t 1000
}

case $1 in
up)
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ -l 1.0

    if wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q '\[MUTED\]'; then
        notif "mute"
    else
        notif "up"
    fi
    ;;

down)
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

    if wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q '\[MUTED\]'; then
        notif "mute"
    else
        notif "down"
    fi
    ;;

mute)
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

    if wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q '\[MUTED\]'; then
        dunstify -a "changevolume" -t 2000 -r 9993 -I "/home/joseph/.local/share/dunst_icons/volume-mute.svg" "" -t 1000
    else
        volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{printf "%.0f%%", $2 * 100}')
        notif "up"
    fi
    ;;
esac
