#!/bin/sh
if [ -f /tmp/outergap ]; then 
    if [ -f /tmp/polybarhidden ]; then
        bspc config top_padding        10 
    else
        bspc config top_padding 46
    fi

    bspc config left_padding           10
    bspc config right_padding          10
    bspc config bottom_padding         10
    rm /tmp/outergap 

else 
    if [ -f /tmp/polybarhidden ]; then
        bspc config top_padding        0 
    else
        bspc config top_padding 36
    fi

    bspc config left_padding           0
    bspc config right_padding          0
    bspc config bottom_padding         0
    touch /tmp/outergap 

fi
