#!/bin/bash
notif () {
    if $(amixer get Capture | grep -q "off"); then
        dunstify -a "mic-tog" -r 9993 -h int:value:"$volume" -I "/home/joseph/.local/share/dunst_icons/mic-off.svg" "${volume}" -t 1000
    else
        dunstify -a "mic-tog" -r 9993 -h int:value:"$volume" -I "/home/joseph/.local/share/dunst_icons/mic.svg" "${volume}" -t 1000
    fi
}

amixer set Capture toggle
notif
