#!/bin/sh
if [ -f /tmp/polybarhidden ]; then 
    if [ -f /tmp/outergap ]; then 
        bspc config top_padding 36 
    else
        bspc config top_padding 46
    fi
    polybar-msg cmd show 
    rm /tmp/polybarhidden 
else 
    if [ -f /tmp/outergap ]; then 
        bspc config top_padding 0 
    else
        bspc config top_padding 10
    fi
    polybar-msg cmd hide 
    touch /tmp/polybarhidden 
fi

