#!/bin/bash
if [ -f "$1" ]; then
    if [ -f "$2" ]; then
        case $1 in 
            *.py) cat $2 | python3 $1                     ;;
            *.cpp) g++ -o ${1%.*} $1; cat $2 | ./${1%.*}  ;;
            *.c) gcc -o ${1%.*} $1 ; cat $2  |./${1%.*}   ;;
            *.java) javac $1 ; cat $2 | java ${1%.*}      ;; 
        esac
    else
        case $1 in 
            *.py) python3 $1                    ;;
            *.cpp) g++ -o ${1%.*} $1; ./${1%.*} ;;
            *.c) gcc -o ${1%.*} $1; ./${1%.*}   ;;
            *.java) javac $1 ; java ${1%.*}     ;;
        esac
    fi
else
    echo "no code"
fi
