#!/bin/sh

id=$(xdotool search --class scpad);
if [ -z "$id" ]; then
        st -c scpad;
else
        if [ ! -f /tmp/hide_scratch ]; then
                touch /tmp/hide_scratch && xdo hide "$id"
        elif [ -f /tmp/hide_scratch ]; then
                rm /tmp/hide_scratch && xdo show "$id"
        fi
fi

