#!/bin/bash
setxkbmap -option caps:escape &
xset -dpms &
xset r rate 215 45 &
setxkbmap us &
fehbg &
setxkbmap us &
xinput set-prop "ELAN0686:00 04F3:320D Touchpad" "Coordinate Transformation Matrix" 1.5 0 0 0 1.5 0 0 0 1 &
xinput --set-prop "ELAN0686:00 04F3:320D Touchpad" 'libinput Accel Profile Enabled' 0, 1
