[bar/main_bar]
modules-left = mod keyboard polywins sep
modules-center = sep sep ewmh sep sep
modules-right = pulseaudio mic sep vpn sep network date time sep
# modules-right = backlight battery pulseaudio mic sep vpn sep network date time sep
