[bar/main_bar]
# monitor=DP-2
modules-left = hidden mod sep title
modules-center = sep sep ewmh sep sep
modules-right = backlight battery pulseaudio mic sep vpn sep network date time
; modules-right = pulseaudio mic sep vpn sep network date time 

[bar/top_bar]

# monitor=DP-0
override-redirect = false
bottom = false
fixed-center = true

modules-center=ewmh
modules-left = hidden mod title

width = 100%
height = 18

offset-x = 0%
offset-y = 0%

background = ${color.background}
foreground = ${color.foreground}

radius-top = 0.0
radius-bottom = 0.0

line-color = ${color.background}

; border-bottom-size = 1px
; border-color = ${color.background}

padding = 0

module-margin-left = 0
module-margin-right = 0

# font-0 = "Source Code Pro Semibold:size=10;4"
font-1 = "icomoon:style=Regular:size=12;2"
font-0 = "Iosevka Nerd Font:stye=Heavy:size=10;2"

dim-value = 1.0

wm-name = bspwm
locale = 

tray-position = right
tray-detached = false
tray-maxsize = 20
tray-background = ${color.background}

tray-offset-x = 0
tray-offset-y = 0

tray-padding = 2
tray-scale = 1.0

wm-restack = bspwm

dpi = 96 

enable-ipc = true
